1 - TORRE SEM TOLDO - H:0.8mts
1 - TORRE COM TOLDO - H:1.2mts
1 - TUNEL DE NIVEL M1
1 - ESCADA M4
1 - ESCADA M1
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCORREGADOR M1
1 - ESCORREGADOR M5
1 - OBSTACULO DE DISCO
1 - COQUEIRO M1
3 - TAMPA M1
1 - PLACA INFORMATIVA
2 - PORTAL M4
