1 - TORRE SEM TOLDO - H:1.0mts
1 - TORRE COM TOLDO - H:1.2mts
2 - FECHAMENTO M1
1 - JOGO DA VELHA
2 - FECHAMENTO M2
1 - ESCADA M3
1 - RAMPA DE AGARRA
1 - TOBOGA M7
1 - COQUEIRO M1
1 - TAMPA M1
1 - PLACA INFORMATIVA
