2 - TORRE SEM TOLDO - H:1.2mts
1 - TOBOGA M7
4 - PORTAL M4
2 - JOGO DA VELHA
4 - FECHAMENTO M1
8 - TAMPA M1
5 - PORTAL M2
1 - ESC VERTICAL ROTO
1 - PLACA INFORMATIVA
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCALADA M2
2 - TUNEL RETO 1M M3
