2 - TORRE COM TOLDO - H:1.2mts
1 - ESCORREGADOR M4
1 - ESCALADA M2
1 - JOGO DA VELHA
1 - BOMBEIRO DE DISCO - DISCO M2
1 - TOBOGA M7
1 - PLACA INFORMATIVA
1 - TEIA DE ARANHA M1
1 - TUNEL RETO 2M M3
1 - PORTAL M4
2 - PORTAL M3
