2 - TORRE COM TOLDO - H:1.2mts
1 - TEIA DE ARANHA M1
1 - ESCORREGADOR M4
1 - PASSARELA CURVA POSITIVA M2
1 - ESCORREGADOR M2
1 - JOGO DA VELHA
1 - PLACA INFORMATIVA
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCALADA M2
2 - PORTAL M3
1 - PORTAL M4
1 - PORTAL M2
