2 - TORRE COM TOLDO - H:1.2mts
1 - TORRE SEM TOLDO - H:1.2mts
2 - TUNEL CURVO M1
1 - PASSARELA CURVA POSITIVA M2
1 - ESCADA DE DISCO M1
1 - ESCALADA M2
1 - TOBOGA M5
6 - FECHAMENTO M1
1 - JOGO DA VELHA
5 - PORTAL M4
1 - FOGUETINHO
2 - FECHAMENTO M2
1 - ESCORREGADOR M4
1 - SKATE ACOP
4 - TAMPA M1
1 - PLACA INFORMATIVA
1 - CARACOL ROTO M1
2 - PORTAL M3
