3 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA CURVA POSITIVA M2
1 - ESCADA DE DISCO M1
1 - FOGUETINHO
1 - TOBOGA M7
1 - ESCORREGADOR M4
1 - ESCALADA M2
1 - PLACA INFORMATIVA
1 - CARACOL ROTO M1
2 - ESC VERTICAL ROTO
3 - PEGA MAO 80CM PINT UNICO
1 - BOMBEIRO M1 - SEM ESC
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCALADA DE CORDAS 2M
1 - PORTAL M4
2 - PORTAL M3
8 - PORTAL M2
