2 - TORRE COM TOLDO - H:1.2mts
1 - TORRE SEM TOLDO - H:1.2mts
1 - TOBOGA M7
1 - ESCADA DE DISCO M1
1 - RAMPA DE AGARRA
1 - FOGUETINHO
1 - ESCORREGADOR M2
1 - CARACOL ROTO M1
1 - TEIA DE ARANHA M1
1 - SKATE ACOP
1 - PASSARELA DE CORDAS 2M
1 - TUNEL RETO 1M
1 - COQUEIRO M1
3 - TAMPA M1
1 - PLACA INFORMATIVA
1 - PORTAL M2
2 - PORTAL M3
2 - FECHAMENTO M1
