3 - TORRE COM TOLDO - H:1.2mts
1 - TORRE SEM TOLDO - H:1.2mts
2 - GANGORRA M1
1 - CARACOL ROTO M1
1 - ESCALADA M2
1 - FOGUETINHO
1 - TEIA DE ARANHA M1
1 - RAMPA DE AGARRA
1 - ESCADA M1
1 - ESCORREGADOR M1
1 - ESCORREGADOR M4
1 - TOBOGA M7
1 - ESCORREGADOR M2
1 - PASSARELA DE CORDAS 2M
1 - PASSARELA FIXA 2M M3
1 - PASSARELA CURVA POSITIVA M2
1 - COQUEIRO M1
1 - PLACA INFORMATIVA
3 - PORTAL M3
2 - PORTAL M4
1 - PORTAL M2
