2 - TORRE SEM TOLDO - H:1.2mts
2 - TORRE COM TOLDO - H:1.2mts
1 - ESCORREGADOR M4
1 - ESCADA M1
1 - COQUEIRO M1
7 - TAMPA M1
1 - JOGO DA VELHA
1 - PASSARELA DE CORDAS 3M
1 - TEIA DE ARANHA M1
1 - ESCORREGADOR M2
1 - TOBOGA M5
1 - BALANCO ACOP M4
2 - CADEIRA BALANCO M3
2 - FECHAMENTO M2
1 - RAMPA DE AGARRA
1 - PLACA INFORMATIVA
1 - SKATE ACOP
2 - PASSARELA FIXA 1M M3
1 - PORTAL M4
1 - PORTAL M3
3 - FECHAMENTO M1
