2 - TORRE COM TOLDO - H:1.2mts
1 - TORRE COM TOLDO - H:0.8mts
1 - PASSARELA FIXA 1M M3 - LATERAL M4
1 - TUNEL DE NIVEL M1
1 - BOMBEIRO M1 - SEM ESC
1 - ESCORREGADOR M1
1 - ESCORREGADOR M5
1 - ESC VERTICAL ROTO
1 - ESCADA M4
1 - TOBOGA M7
1 - JOGO DA VELHA
1 - PLACA INFORMATIVA
4 - BARRA RETA 1M PINT
1 - BALANCO ACOP M4
1 - CADEIRA BALANCO M3
1 - CADEIRA BALANCO M2
2 - PORTAL M4
3 - PORTAL M2
1 - FECHAMENTO M1
