3 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA FIXA 2M M3
1 - PASSARELA DE CORDAS 2M
1 - BOMBEIRO DE DISCO - DISCO M2
1 - TEIA DE ARANHA M1
1 - ESCADA M1
1 - ESCORREGADOR M4
1 - ESCORREGADOR M1
1 - TOBOGA M5
2 - FECHAMENTO M2
1 - JOGO DA VELHA
1 - PLACA INFORMATIVA
1 - PORTAL M3
2 - PORTAL M4
