2 - TORRE COM TOLDO - H:1.2mts
1 - TORRE SEM TOLDO - H:1.2mts
1 - PASSARELA CURVA POSITIVA M2
1 - PASSARELA DE CORDAS 2M
1 - ESCADA DE DISCO M1
1 - FOGUETINHO
1 - TOBOGA M7
1 - ESCORREGADOR M4
1 - JOGO DA VELHA
4 - TAMPA M1
2 - FECHAMENTO M2
1 - ESCALADA M2
1 - PLACA INFORMATIVA
1 - CARACOL ROTO M1
1 - PORTAL M4
2 - PORTAL M3
