3 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA CURVA POSITIVA M2
1 - ESCORREGADOR M4
1 - ESCORREGADOR M2
1 - TOBOGA M7
1 - ESCORREGADOR M1
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCADA M1
1 - ESCALADA M2
1 - JOGO DA VELHA
8 - FECHAMENTO M2
1 - PLACA INFORMATIVA
2 - TUNEL RETO 2M M3
2 - PORTAL M4
1 - PORTAL M3
