3 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA FIXA 2M M3
1 - ESCADA M1
1 - RAMPA DE AGARRA
2 - ESCORREGADOR M1
1 - TOBOGA M7
1 - ESCORREGADOR M2
1 - BALANCO ACOP M4
1 - CADEIRA BALANCO M2
1 - CADEIRA BALANCO M3
1 - JOGO DA VELHA
1 - PLACA INFORMATIVA
1 - TUNEL CURVO M3
2 - PORTAL M4
1 - FECHAMENTO M1
