3 - TORRE COM TOLDO - H:1.2mts
2 - CADEIRA BALANCO M3
2 - ESCORREGADOR M1
1 - PASSARELA CURVA POSITIVA M2
1 - PLACA INFORMATIVA
1 - TOBOGA M5
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCADA M1
1 - RAMPA DE AGARRA
1 - TEIA DE ARANHA M1
1 - BALANCO ACOP M4
1 - TUNEL RETO 2M M3
2 - PORTAL M4
1 - PORTAL M3
1 - FECHAMENTO M1
