3 - TORRE COM TOLDO - H:1.2mts
1 - TEIA DE ARANHA M1
1 - PASSARELA DE CORDAS 3M
2 - ESCORREGADOR M1
1 - BALANCO ACOP M4
2 - CADEIRA BALANCO M3
1 - PLACA INFORMATIVA
1 - TOBOGA M5
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCADA M1
1 - RAMPA DE AGARRA
1 - PASSARELA FIXA 2M M3
1 - PORTAL M3
2 - PORTAL M4
1 - FECHAMENTO M1
