3 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA FIXA 2M M3
1 - TOBOGA M7
1 - ESCORREGADOR M2
1 - CARACOL ROTO M1
1 - ESCADA M1
1 - TEIA DE ARANHA M1
1 - BOMBEIRO DE DISCO - DISCO M2
1 - RAMPA DE AGARRA
1 - ESCALADA M2
1 - PLACA INFORMATIVA
1 - TUNEL RETO 2M M3
3 - PORTAL M3
