3 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA DE CORDAS 2M
4 - FECHAMENTO M1
1 - JOGO DA VELHA
1 - ESCORREGADOR M4
1 - ESCORREGADOR M1
1 - TOBOGA M7
1 - TEIA DE ARANHA M1
1 - ESCADA M1
1 - BOMBEIRO DE DISCO - DISCO M2
1 - PLACA INFORMATIVA
1 - ESCALADA M2
2 - TUNEL RETO 2M M3
2 - PORTAL M4
2 - PORTAL M3
