1 - TORRE COM TOLDO - H:1.0mts
1 - TORRE COM TOLDO - H:0.8mts
2 - TORRE SEM TOLDO - H:1.2mts
1 - TOBOGA M7
4 - TAMPA M1
1 - PLACA INFORMATIVA
1 - PASSARELA DE CORDAS 1M
1 - PASSARELA CURVA POSITIVA M2
2 - JOGO DA VELHA
1 - FOGUETINHO
2 - FECHAMENTO M2
2 - FECHAMENTO M1
1 - ESCORREGADOR M5
1 - ESCORREGADOR M3
1 - ESCADA M4
2 - COQUEIRO M1
1 - BOMBEIRO DE DISCO - DISCO M2
2 - PORTAL M4
