2 - TORRE SEM TOLDO - H:1.2mts
2 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA FIXA 3M M3
1 - PASSARELA CURVA POSITIVA M2
1 - PASSARELA DE CORDAS 3M
1 - ESCALADA M2
1 - TEIA DE ARANHA M1
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCADA M1
1 - RAMPA DE AGARRA
1 - TOBOGA M7
1 - ESCORREGADOR M2
1 - ESCORREGADOR M4
1 - CARACOL ROTO M1
1 - BALANCO ACOP M4
2 - CADEIRA BALANCO M3
2 - COQUEIRO M1
6 - TAMPA M1
1 - PLACA INFORMATIVA
3 - PORTAL M3
1 - PORTAL M4
1 - FECHAMENTO M1
