4 - TORRE COM TOLDO - H:0.8mts
1 - PASSARELA CURVA POSITIVA M2
2 - PASSARELA FIXA 2M M3
2 - ESCADA M4
2 - TOBOGA M4
2 - ESCORREGADOR M5
2 - TEIA DE ARANHA M2
2 - JOGO DA VELHA
1 - PLACA INFORMATIVA
2 - PORTAL M4
2 - PORTAL M3
