4 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA FIXA 2M M3
1 - PASSARELA CURVA POSITIVA M2
1 - BOMBEIRO DE DISCO - DISCO M2
2 - ESCALADA M2
1 - TEIA DE ARANHA M1
1 - ESCORREGADOR M1
1 - ESCORREGADOR M4
1 - ESCORREGADOR M2
1 - TOBOGA M5
1 - TOBOGA M7
1 - JOGO DA VELHA
1 - PLACA INFORMATIVA
1 - TUNEL RETO 2M M3
3 - PORTAL M3
2 - PORTAL M4
