1 - TORRE SEM TOLDO - H:1.2mts
2 - TORRE COM TOLDO - H:1.2mts
1 - TORRE COM TOLDO - H:0.8mts
3 - TAMPA M1
1 - COQUEIRO M1
1 - PASSARELA CURVA POSITIVA M2
1 - PASSARELA DE CORDAS 2M
1 - ACESSO DE NIVEL
1 - RAMPA DE AGARRA
1 - TEIA DE ARANHA M1
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCADA M4
1 - ESCORREGADOR M4
1 - TOBOGA M7
1 - ESCORREGADOR M1
1 - ESCORREGADOR M5
2 - FECHAMENTO M2
1 - JOGO DA VELHA
1 - PLACA INFORMATIVA
1 - PORTAL M5
3 - PORTAL M4
