3 - TORRE COM TOLDO - H:1.2mts
1 - TORRE COM TOLDO - H:0.8mts
1 - ESCORREGADOR M5
1 - JOGO DA VELHA
2 - ESCALADA M2
2 - ESCORREGADOR M1
1 - TEIA DE ARANHA M2
2 - FECHAMENTO M2
1 - PASSARELA DE CORDAS 1M
1 - ESCADA VERTICAL PINT
1 - TUNEL RETO 1M
2 - FECHAMENTO M1
1 - PLACA INFORMATIVA
1 - PASSARELA FIXA 1M M3
3 - PORTAL M4
3 - PORTAL M3
