4 - TORRE COM TOLDO - H:1.2mts
1 - ESCADA DE DISCO M1
1 - ESCORREGADOR M2
1 - BALANCO ACOP M4
2 - CADEIRA BALANCO M3
1 - TEIA DE ARANHA M1
1 - PLACA INFORMATIVA
1 - RAMPA DE AGARRA
1 - BOMBEIRO DE DISCO - DISCO M2
1 - ESCADA M1
1 - TOBOGA M5
2 - PASSARELA FIXA 2M M3
2 - TUNEL RETO 2M M3
1 - FECHAMENTO M1
1 - PORTAL M3
