5 - TORRE COM TOLDO - H:0.8mts
1 - PASSARELA CURVA POSITIVA M2
1 - RAMPA DE AGARRA
1 - ESCADA M4
1 - RAMPA DE NO M3
1 - PASSARELA FIXA 2M M3
1 - ESCORREGADOR M5
2 - TOBOGA M4
8 - FECHAMENTO M2
2 - JOGO DA VELHA
1 - PLACA INFORMATIVA
1 - PASSARELA DE CORDAS 2M
1 - TUNEL RETO 2M M3
1 - PORTAL M4
