4 - TORRE COM TOLDO - H:0.8mts
1 - TORRE COM TOLDO - H:0.45mts
2 - ESCORREGADOR M5
1 - TEIA DE ARANHA M2
2 - TOBOGA M4
1 - PASSARELA CURVA POSITIVA M2
2 - PASSARELA FIXA 2M M3
1 - ESCADA M4
1 - PASSARELA DE CORDAS 2M
1 - MEIO CARACOL M1
1 - JOGO DA VELHA
1 - OBSTACULO DE DISCO
2 - ESCALADA M3
1 - RAMPA DE AGARRA
1 - PLACA INFORMATIVA
1 - PEGA MAO 80CM PINT
2 - PORTAL M4
4 - PORTAL M3
