2 - TORRE COM TOLDO - H:1.2mts
1 - TORRE COM TOLDO - H:0.8mts
1 - PASSARELA FIXA 2M M3
1 - PASSARELA DE CORDAS 2M
1 - ACESSO DE NIVEL
1 - CIRCUITO DE DISCO AVULSO
1 - ESCADA M4
1 - BOMBEIRO DE DISCO - DISCO M2
1 - CARACOL ROTO M1
1 - TOBOGA M7
1 - ESCORREGADOR M5
2 - JOGO DA VELHA
1 - PLACA INFORMATIVA
1 - PORTAL M5
3 - PORTAL M2
5 - PORTAL M3
1 - PORTAL M4
