5 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA FIXA 3M M3
1 - PASSARELA DE CORDAS 2M
1 - PASSARELA CURVA POSITIVA M2
1 - TUNEL RETO 1M
1 - RAMPA DE NO M3
1 - ESCADA M1
1 - ESCALADA M2
1 - TEIA DE ARANHA M1
1 - BOMBEIRO DE DISCO - DISCO M2
1 - RAMPA DE AGARRA
2 - TOBOGA M7
1 - ESCORREGADOR M2
1 - CARACOL ROTO M1
1 - JOGO DA VELHA
1 - BALANCO ACOP M4
2 - CADEIRA BALANCO M3
1 - PLACA INFORMATIVA
3 - PORTAL M3
1 - FECHAMENTO M1
