5 - TORRE COM TOLDO - H:1.2mts
1 - PASSARELA CURVA POSITIVA M2
1 - PASSARELA DE CORDAS 2M
1 - ESCORREGADOR M1
1 - TOBOGA M7
1 - TEIA DE ARANHA M1
1 - ESCADA M1
1 - ESCORREGADOR M4
1 - BALANCO ACOP M4
1 - BOMBEIRO M1 - SEM ESC
2 - CADEIRA BALANCO M3
3 - FECHAMENTO M1
1 - PLACA INFORMATIVA
4 - BARRA RETA 1M PINT
1 - RAMPA DE NO M3
1 - CARACOL ROTO M1
1 - TUNEL RETO 2M M3
2 - PORTAL M4
2 - PORTAL M3
