4 - TORRE COM TOLDO - H:1.2mts
1 - TUNEL RETO 2M M2
1 - TUNEL CURVO M2
1 - PASSARELA CURVA POSITIVA M2
1 - PASSARELA DE CORDAS 2M
1 - CIRCUITO DE DISCO AVULSO
1 - RAMPA DE AGARRA
1 - ESCADA M1
1 - CARACOL ROTO M1
2 - FECHAMENTO M2
1 - TEIA DE ARANHA M1
1 - ESCORREGADOR M1
1 - TOBOGA M7
1 - RAMPA DE TACOS M3
1 - ESCORREGADOR M4
1 - PLACA INFORMATIVA
3 - PORTAL M2
6 - PORTAL M3
2 - PORTAL M4
