1 - TORRE COM TOLDO - H:0.8mts
1 - TORRE SEM TOLDO - H:1.2mts
1 - ACESSO DE NIVEL
1 - ESCALADA M3
4 - FECHAMENTO M2
1 - ESCORREGADOR M5
1 - RAMPA DE AGARRA
1 - COQUEIRO M1
3 - TAMPA M1
1 - ESCORREGADOR M4
3 - PORTAL M5
1 - PLACA INFORMATIVA
2 - PORTAL M4
